fixes

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -2,10 +2,21 @@
 # The actual `bin/test-compile` code lives in `bin/ruby_test-compile`. This file instead
 # bootstraps the ruby needed and then executes `bin/ruby_test-compile`
 
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
 BIN_DIR=$(cd $(dirname $0); pwd)
 BUILDPACK_DIR=$(dirname $BIN_DIR)
+
+if [ ! -f "${ENV_DIR}/APP_BASE" ]; then
+    echo "APP_BASE was not set. Aborting"
+    exit 1
+fi
+APP_BASE="$(cat "${ENV_DIR}/APP_BASE")"
+APP_DIR="$BUILD_DIR/$APP_BASE"
+
 
 source "$BIN_DIR/support/bash_functions.sh"
 heroku_buildpack_ruby_install_ruby "$BIN_DIR" "$BUILDPACK_DIR"
 
-$heroku_buildpack_ruby_dir/bin/ruby $BIN_DIR/support/ruby_test $@
+$heroku_buildpack_ruby_dir/bin/ruby $BIN_DIR/support/ruby_test $APP_DIR $2 $3 
diff --git a/bin/test-compile b/bin/test-compile
--- a/bin/test-compile
+++ b/bin/test-compile
@@ -8,10 +8,17 @@ ENV_DIR=$3
 BIN_DIR=$(cd $(dirname $0); pwd)
 BUILDPACK_DIR=$(dirname $BIN_DIR)
 
+if [ ! -f "${ENV_DIR}/APP_BASE" ]; then
+    echo "APP_BASE was not set. Aborting"
+    exit 1
+fi
+APP_BASE="$(cat "${ENV_DIR}/APP_BASE")"
+APP_DIR="$BUILD_DIR/$APP_BASE"
+
 source "$BIN_DIR/support/bash_functions.sh"
 heroku_buildpack_ruby_install_ruby "$BIN_DIR" "$BUILDPACK_DIR"
 
-if detect_needs_java "$BUILD_DIR"; then
+if detect_needs_java "$APP_DIR"; then
   cat <<EOM
 
        ## Warning: Your app needs java
@@ -25,7 +32,7 @@ if detect_needs_java "$BUILD_DIR"; then
 
 EOM
 
-  compile_buildpack_v2 "$BUILD_DIR" "$CACHE_DIR" "$ENV_DIR" "https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/jvm.tgz" "heroku/jvm"
+  compile_buildpack_v2 "$APP_DIR" "$CACHE_DIR" "$ENV_DIR" "https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/jvm.tgz" "heroku/jvm"
 fi
 
-$heroku_buildpack_ruby_dir/bin/ruby $BIN_DIR/support/ruby_test-compile $@
+$heroku_buildpack_ruby_dir/bin/ruby $BIN_DIR/support/ruby_test-compile $APP_DIR $2 $3
